name: Audit

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    name: Audit Dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      
      - name: Restore cache
        id: cache
        uses: actions/cache@v3.0.4
        with:
          path: |
            .yarn/
          key: ${{ hashFiles('**/yarn.lock') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: |
          yarn list

      - name: Run Audit
        run: yarn ci --cache-dir .yarn/ && yarn audit
  