name: Test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18.x
    name: Execute (chrome)
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}
      
      - name: Restore cache
        id: cache
        uses: actions/cache@v3.0.4
        with:
          path: |
            .yarn/
          key: ${{ hashFiles('**/yarn.lock') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: |
          yarn list

      - name: Run tests
        run: | 
          yarn ci --cache-dir .yarn/
          yarn test:acceptance:desktop
  